# Generated by Django 3.1.4 on 2020-12-13 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artists', '0002_artist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('user_id', 'spotify_id')},
        ),
    ]
