# Generated by Django 3.1.4 on 2020-12-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20201213_2141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set(),
        ),
    ]
