# Generated by Django 3.1.4 on 2020-12-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_artist_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('spotify_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('artist_spotify_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('album', models.CharField(blank=True, max_length=100)),
                ('youtube_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artist')),
            ],
        ),
    ]
