# Generated by Django 3.1.4 on 2020-12-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_spotify_id',
        ),
    ]
