# Generated by Django 3.1.4 on 2020-12-12 05:35

from django.db import migrations, models
import songs.validators.difficulty_validator


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_artist_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='difficult',
            field=models.IntegerField(default=0, validators=[songs.validators.difficulty_validator.validate_difficulty]),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('Folk', 'Folk'), ('Country', 'Country'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('Classical', 'Classical'), ('Jazz', 'Jazz')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='instrument',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano')], default='Guitar', max_length=25),
        ),
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Proficient')], default=1),
        ),
    ]
