# Generated by Django 3.1.4 on 2020-12-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20201212_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='difficult',
            new_name='difficulty',
        ),
    ]
