# Generated by Django 3.1.4 on 2020-12-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20201212_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('Alternative', 'Alternative'), ('Folk', 'Folk'), ('Country', 'Country'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('Classical', 'Classical'), ('Jazz', 'Jazz')], default='', max_length=20),
        ),
    ]
